export const terminalOutput = [
  { style: "cmd", text: "Running automated workflow sync..." },
  { style: "info", text: "→ Connecting to booking system API" },
  { style: "ok", text: "✓ Connected successfully" },
  { style: "info", text: "→ Syncing customer records" },
  { style: "data", text: "Processing: 127 new appointments" },
  { style: "data", text: "Updated: 43 customer profiles" },
  { style: "data", text: "Sent: 89 reminder notifications" },
  { style: "info", text: "→ Generating billing reports" },
  { style: "ok", text: "✓ Export completed: monthly_revenue.pdf" },
  { style: "sep", text: "" },
  { style: "ok", text: "✓ Workflow completed" },
  { style: "accent", text: "Time saved: 3.5 hours" },
  { style: "cursor", text: "$ _" },
];
